In [3]:
#E-commerce Data Analysis Project
#Import+Load Data
import pandas as pd

In [4]:
path="C:/Users/simpi/Downloads/archive/"
orders=pd.read_csv(path+"olist_orders_dataset.csv")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [5]:
customers=pd.read_csv(path+"olist_customers_dataset.csv")
order_items=pd.read_csv(path+"olist_order_items_dataset.csv")
payments=pd.read_csv(path+"olist_order_payments_dataset.csv")

In [6]:
customers.head()
order_items.head()
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [7]:
orders=orders[orders['order_status']=='delivered']

In [8]:
orders=orders.dropna(subset=['order_id','customer_id'])

In [9]:
order_items=order_items.dropna(subset=['order_id','price'])

In [10]:
payments=payments.dropna(subset=['order_id','payment_value'])

In [11]:
orders['order_purchases_timestamp']=pd.to_datetime(orders['order_purchase_timestamp'])

In [12]:
#Merging orders and customers
df=pd.merge(orders,customers,on='customer_id',how='left')

In [13]:
df[['order_id','customer_id','customer_city']].head(10)

,order_id,customer_id,customer_city
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,sao paulo
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,barreiras
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,vianopolis
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,sao goncalo do amarante
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,santo andre
5,a4591c265e18cb1dcee52889e2d8acc3,503740e9ca751ccdda7ba28e9ab8f608,congonhinhas
6,6514b8ad8028c9f2cc2374ded245783f,9bdf08b4b3b52b5526ff42d37d47f222,nilopolis
7,76c6e866289321a7c93b82b54852dc33,f54a9f0e6b351c431402b8461ea51999,faxinalzinho
8,e69bfb5eb88e0ed6a785585b27e16dbf,31ad1d1b63eb9962463f764d4e6e0c9d,sorocaba
9,e6ce16cb79ec1d90b1da9085a6118aeb,494dded5b201313c64ed7f100595b95c,rio de janeiro

In [14]:
#Add order items
df=pd.merge(df,order_items,on='order_id',how='left')

In [15]:
df=pd.merge(df,payments,on='order_id',how='left')

In [16]:
df.shape
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchases_timestamp,customer_unique_id,...,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,payment_sequential,payment_type,payment_installments,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2017-10-02 10:56:33,7c396fd4830fd04220f754e42b4e5bff,...,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,1.0,credit_card,1.0,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2017-10-02 10:56:33,7c396fd4830fd04220f754e42b4e5bff,...,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,3.0,voucher,1.0,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2017-10-02 10:56:33,7c396fd4830fd04220f754e42b4e5bff,...,1,87285b34884572647811a353c7ac498a,3504c0cb71d7fa48d967e0e4c94d59d9,2017-10-06 11:07:15,29.99,8.72,2.0,voucher,1.0,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2018-07-24 20:41:37,af07308b275d755c9edb36a90c618231,...,1,595fac2a385ac33a80bd5114aec74eb8,289cdb325fb7e7f891c38608bf9e0962,2018-07-30 03:24:27,118.70,22.76,1.0,boleto,1.0,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2018-08-08 08:38:49,3a653a41f6f9fc3d2a113cf8398680e8,...,1,aa4383b373c6aca5d8797843e5594415,4869f7a5dfa277a7dca6462dcf3b52b2,2018-08-13 08:55:23,159.90,19.22,1.0,credit_card,3.0,179.12

In [17]:
#Grouping
payments_grouped =(
payments.groupby('order_id')
['payment_value'].sum().reset_index()
)

In [ ]:
payments_grouped.head("10")

                           order_id  payment_value
0  00010242fe8c5a6d1ba2dd792cb16214          72.19
1  00018f77f2f0320c557190d7a144bdd3         259.83
2  000229ec398224ef6ca0657da4fc703e         216.87
3  00024acbcdf0a6daa1e931b038114c75          25.78
4  00042b26cf59d7ce69dfabb4e55b4fd9         218.04
5  00048cc3ae777c65dbb7d2a0634bc1ea          34.59
6  00054e8431b9d7675808bcb819fb4a32          31.75
7  000576fe39319847cbb9d288c5617fa6         880.75
8  0005a1a1728c9d785b8e2b08b904576c         157.60
9  0005f50442cb953dcd1d21e1fb923495          65.39

In [19]:
#Feature Engineering 
#force conversion
df['order_delivered_customer_date']=(
pd.to_datetime(df['order_delivered_customer_date'])
)

df['order_purchase_timestamp']=(
pd.to_datetime(df['order_purchase_timestamp'])
)

In [20]:
#delivery time
df['delivery_time']=(
    
df['order_delivered_customer_date'] -
df['order_purchase_timestamp']
).dt.days

In [21]:
#force conversion
df['order_delivered_customer_date']=(
pd.to_datetime(df['order_delivered_customer_date'],errors='coerce')
)
df['order_estimated_delivery_date']=(
pd.to_datetime(df['order_estimated_delivery_date'],errors='coerce')
)

In [22]:
#Delay
df['delay']=(
   
df['order_delivered_customer_date']-
df['order_estimated_delivery_date']
).dt.days

In [23]:
#order month
df['order_month']=(
df['order_purchase_timestamp'].dt.to_period('M')
)

In [24]:
#total order value
df.rename(columns={'payment_value':'total_order_value'},inplace=True)

In [25]:
#Business Analysis
#total revenue
df['total_order_value'].sum()

np.float64(19776160.439999998)

In [26]:
#monthly revenue trend
df.groupby('order_month')['total_order_value'].sum()

order_month
2016-09          0.00
2016-10      61746.94
2016-12         19.62
2017-01     176491.49
2017-02     325782.66
2017-03     505735.83
2017-04     456108.32
2017-05     701313.60
2017-06     585400.98
2017-07     716069.98
2017-08     842689.94
2017-09     996279.59
2017-10     998609.62
2017-11    1548682.69
2017-12    1020067.26
2018-01    1374064.02
2018-02    1279970.45
2018-03    1435458.33
2018-04    1466607.15
2018-05    1480667.59
2018-06    1285926.11
2018-07    1307228.18
2018-08    1211240.09
Freq: M, Name: total_order_value, dtype: float64

In [27]:
#Average delivery time
df['delivery_time'].mean()

np.float64(12.018873337390247)

In [28]:
#late delivery %
(df['delay']>0).mean()*100

np.float64(6.544793894191485)

In [29]:
#top cities by order
df['customer_city'].value_counts().head(10)

customer_city
sao paulo                18163
rio de janeiro            7950
belo horizonte            3188
brasilia                  2405
curitiba                  1785
campinas                  1707
porto alegre              1615
salvador                  1473
guarulhos                 1364
sao bernardo do campo     1093
Name: count, dtype: int64

In [30]:
#Payment type analysis
df['payment_type'].value_counts()

payment_type
credit_card    84896
boleto         22362
voucher         6123
debit_card      1654
Name: count, dtype: int64

In [31]:
!pip install openpyxl

Requirement already satisfied: openpyxl in C:\Users\simpi\miniconda3\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\simpi\miniconda3\Lib\site-packages (from openpyxl) (2.0.0)

In [32]:
df.to_csv("final_cleaned_data.csv",index=False)

In [33]:
import os
os.getcwd()

'c:\\Users\\simpi\\Desktop\\python'